"""Flow promotion bridge.

Exposes a thin REST surface that drives the official Langflow Flow DevOps
Toolkit (the ``lfx`` CLI, >= 0.4.x) to promote flows from this local instance
to remote Langflow environments (e.g. staging, production).

Design notes:
- "dev" is *this* Langflow instance; a flow lives in our database. To promote
  it we export the flow to a temporary JSON file and run ``lfx push`` / ``lfx
  status`` against the chosen remote environment.
- The official ``lfx`` is invoked as an isolated subprocess via ``uvx`` so it
  never collides with the ``lfx`` package vendored inside langflow-base. The
  command can be overridden with ``LANGFLOW_DEVOPS_LFX_BIN`` (e.g. a path to a
  pre-installed binary in an air-gapped deployment).
- Remote connections are stored per-user in an ``environments.yaml`` file.
  The API key is entered once in the UI and stored encrypted at rest using
  Langflow's Fernet secret mechanism (the same ``SECRET_KEY`` used for API
  keys); the plaintext value is never persisted or returned to clients.
- Legacy entries that reference an environment-variable name (``api_key_env``)
  are still honored for backward compatibility.
- ``lfx push`` upserts by stable flow id and strips secrets by default, so
  promotion moves the flow graph only and the target supplies its own secrets.
"""

from __future__ import annotations

import asyncio
import json
import os
import shlex
import tempfile
from pathlib import Path
from typing import Annotated
from uuid import UUID

import yaml
from fastapi import APIRouter, HTTPException, Query
from lfx.log import logger
from pydantic import BaseModel, Field
from sqlmodel import select

from langflow.api.utils import CurrentActiveUser, DbSessionReadOnly
from langflow.services.auth.utils import decrypt_api_key, encrypt_api_key
from langflow.services.database.models.flow.model import Flow
from langflow.services.deps import get_settings_service

router = APIRouter(prefix="/promote", tags=["Promotion"])

# Default pinned version of the official Flow DevOps Toolkit. Override with
# LANGFLOW_DEVOPS_LFX_VERSION, or bypass uvx entirely with LANGFLOW_DEVOPS_LFX_BIN.
DEFAULT_LFX_VERSION = "0.4.6"
# Generous timeout: the first uvx invocation may download the package.
LFX_TIMEOUT_SECONDS = 180


# --------------------------------------------------------------------------- #
# Schemas
# --------------------------------------------------------------------------- #
class EnvironmentInfo(BaseModel):
    name: str = Field(description="Environment name, e.g. 'staging' or 'production'.")
    url: str = Field(description="Base URL of the remote Langflow instance.")
    has_api_key: bool = Field(description="Whether a usable API key is stored for this environment.")


class EnvironmentInput(BaseModel):
    name: str = Field(min_length=1, description="Environment name, e.g. 'production'.")
    url: str = Field(min_length=1, description="Base URL of the remote Langflow instance.")
    api_key: str = Field(min_length=1, description="The remote API key value; stored encrypted, never returned.")


class EnvironmentListResponse(BaseModel):
    environments: list[EnvironmentInfo]


class LoginRequest(BaseModel):
    env: str


class LoginResponse(BaseModel):
    ok: bool
    message: str


class StatusResponse(BaseModel):
    env: str
    flow_id: UUID
    status: str = Field(description="One of: synced, ahead, behind, new, no-id, error, unknown.")
    detail: str = ""


class PromoteRequest(BaseModel):
    flow_id: UUID
    env: str
    project: str | None = Field(default=None, description="Optional target project name on the remote.")


class PromoteResponse(BaseModel):
    ok: bool
    message: str
    output: str = ""


# --------------------------------------------------------------------------- #
# Project dir + environments.yaml helpers
# --------------------------------------------------------------------------- #
_DEFAULT_ENVIRONMENTS_YAML = (
    "# Flow DevOps environments managed by Langflow.\n"
    "# Each entry points at a remote Langflow instance. The API key is stored in\n"
    "# 'api_key_encrypted' (Fernet-encrypted with the server SECRET_KEY); the\n"
    "# plaintext is never written here. Do not edit this file by hand.\n"
    "# (Legacy 'api_key_env' entries naming an environment variable still work.)\n"
)


def _devops_root() -> Path:
    config_dir = get_settings_service().settings.config_dir or str(Path.home() / ".langflow")
    return Path(config_dir) / "devops"


def _project_dir(user_id: UUID) -> Path:
    """Return (and lazily create) the per-user lfx project directory."""
    project = _devops_root() / str(user_id)
    (project / "flows").mkdir(parents=True, exist_ok=True)
    (project / ".lfx").mkdir(parents=True, exist_ok=True)
    env_file = project / ".lfx" / "environments.yaml"
    if not env_file.exists():
        env_file.write_text(_DEFAULT_ENVIRONMENTS_YAML, encoding="utf-8")
    return project


def _environments_file(user_id: UUID) -> Path:
    return _project_dir(user_id) / ".lfx" / "environments.yaml"


def _load_environments(user_id: UUID) -> dict[str, dict]:
    path = _environments_file(user_id)
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError) as exc:
        raise HTTPException(status_code=500, detail=f"Could not read environments file: {exc}") from exc
    if not isinstance(raw, dict):
        return {}
    # Filter to well-formed entries only: a URL plus either an encrypted key
    # (current format) or a legacy env-var name.
    return {
        name: entry
        for name, entry in raw.items()
        if isinstance(entry, dict) and entry.get("url") and (entry.get("api_key_encrypted") or entry.get("api_key_env"))
    }


def _write_environments(user_id: UUID, environments: dict[str, dict]) -> None:
    """Persist the full per-user environments mapping (entries already shaped for disk)."""
    path = _environments_file(user_id)
    try:
        path.write_text(_DEFAULT_ENVIRONMENTS_YAML + yaml.safe_dump(environments, sort_keys=True), encoding="utf-8")
    except OSError as exc:
        raise HTTPException(status_code=500, detail=f"Could not write environments file: {exc}") from exc


def _resolve_env_or_404(user_id: UUID, env_name: str) -> dict:
    environments = _load_environments(user_id)
    entry = environments.get(env_name)
    if not entry:
        raise HTTPException(status_code=404, detail=f"Environment '{env_name}' not found.")
    return entry


def _decrypt_stored_key(encrypted: str) -> str:
    """Decrypt a stored key; returns empty string if it cannot be decrypted."""
    try:
        return decrypt_api_key(encrypted) or ""
    except Exception:  # noqa: BLE001 - decryption can fail if SECRET_KEY changed
        return ""


def _entry_has_api_key(entry: dict) -> bool:
    """Whether a usable API key can be resolved for this environment."""
    if entry.get("api_key_encrypted"):
        return bool(_decrypt_stored_key(entry["api_key_encrypted"]))
    if entry.get("api_key_env"):
        return bool(os.environ.get(entry["api_key_env"]))
    return False


def _resolve_api_key(entry: dict) -> str:
    """Resolve the plaintext API key for an environment entry.

    Prefers the encrypted-at-rest value; falls back to a legacy env-var name.
    """
    encrypted = entry.get("api_key_encrypted")
    if encrypted:
        key = _decrypt_stored_key(encrypted)
        if not key:
            raise HTTPException(
                status_code=400,
                detail=(
                    "Stored API key could not be decrypted. This usually means the server SECRET_KEY "
                    "changed since the environment was saved. Remove and re-add the environment."
                ),
            )
        return key
    legacy_env = entry.get("api_key_env")
    if legacy_env:
        key = os.environ.get(legacy_env)
        if not key:
            raise HTTPException(
                status_code=400,
                detail=f"API key env var '{legacy_env}' is not set on the Langflow server.",
            )
        return key
    raise HTTPException(status_code=400, detail="No API key is configured for this environment.")


# --------------------------------------------------------------------------- #
# lfx subprocess helpers
# --------------------------------------------------------------------------- #
def _lfx_base_command() -> list[str]:
    """Return the base argv for invoking the official lfx CLI.

    Honors LANGFLOW_DEVOPS_LFX_BIN (a custom executable, possibly with args) and
    LANGFLOW_DEVOPS_LFX_VERSION (the uvx-pinned version). Defaults to uvx.
    """
    custom = os.environ.get("LANGFLOW_DEVOPS_LFX_BIN")
    if custom:
        return shlex.split(custom)
    version = os.environ.get("LANGFLOW_DEVOPS_LFX_VERSION", DEFAULT_LFX_VERSION)
    return ["uvx", f"lfx@{version}"]


def _clean_subprocess_env() -> dict[str, str]:
    """Build a clean environment for invoking the isolated lfx via uvx.

    The Langflow backend is typically launched through ``uv run``, which sets
    ``VIRTUAL_ENV`` and ``UV_RUN_RECURSION_DEPTH``. Inheriting those makes a
    nested ``uvx`` resolve/build into a degraded environment (slow, and it can
    pick up the active venv), so we strip them and force a fresh, isolated run.
    """
    env = {**os.environ, "NO_COLOR": "1", "TERM": "dumb"}
    for var in ("VIRTUAL_ENV", "UV_RUN_RECURSION_DEPTH", "PYTHONHOME", "PYTHONPATH"):
        env.pop(var, None)
    return env


def _redact(args: list[str]) -> list[str]:
    """Return args with the value following --api-key redacted, for logging."""
    redacted = list(args)
    for i, a in enumerate(redacted[:-1]):
        if a == "--api-key":
            redacted[i + 1] = "***"
    return redacted


async def _run_lfx(args: list[str], cwd: Path) -> tuple[int, str, str]:
    """Run an lfx command, returning (returncode, stdout, stderr)."""
    cmd = [*_lfx_base_command(), *args]
    env = _clean_subprocess_env()
    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            cwd=str(cwd),
            env=env,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout_b, stderr_b = await asyncio.wait_for(proc.communicate(), timeout=LFX_TIMEOUT_SECONDS)
    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=500,
            detail="Could not launch the lfx DevOps CLI. Ensure 'uvx' is installed or set LANGFLOW_DEVOPS_LFX_BIN.",
        ) from exc
    except asyncio.TimeoutError as exc:
        raise HTTPException(status_code=504, detail="The lfx command timed out.") from exc
    stdout = stdout_b.decode(errors="replace")
    stderr = stderr_b.decode(errors="replace")
    code = proc.returncode or 0
    logger.debug(
        f"lfx command {_redact(cmd)} exited {code}; stdout={stdout.strip()[:500]!r} stderr={stderr.strip()[:500]!r}"
    )
    return code, stdout, stderr


def _flow_export_dict(flow: Flow) -> dict:
    """Serialize a flow into the JSON shape lfx expects (stable id + graph data)."""
    return {
        "id": str(flow.id),
        "name": flow.name,
        "description": flow.description or "",
        "data": flow.data or {"nodes": [], "edges": []},
        "is_component": bool(flow.is_component),
        "endpoint_name": flow.endpoint_name,
    }


async def _fetch_user_flow(session, user_id: UUID, flow_id: UUID) -> Flow:
    flow = (await session.exec(select(Flow).where(Flow.id == flow_id, Flow.user_id == user_id))).first()
    if not flow:
        raise HTTPException(status_code=404, detail="Flow not found.")
    return flow


_STATUS_TOKENS = ("synced", "behind", "ahead", "new", "no id", "remote only", "error")


def _parse_status(stdout: str) -> tuple[str, str]:
    """Best-effort parse of `lfx status` output into a single status token.

    lfx renders a rich table; we look for the known status labels. Returns
    (status, detail). Falls back to ('unknown', '') when nothing matches.
    """
    text = stdout.lower()
    for token in _STATUS_TOKENS:
        if token in text:
            return token.replace(" ", "-"), ""
    return "unknown", ""


# --------------------------------------------------------------------------- #
# Endpoints
# --------------------------------------------------------------------------- #
@router.get("/environments", response_model=EnvironmentListResponse)
async def list_environments(current_user: CurrentActiveUser) -> EnvironmentListResponse:
    """List configured remote environments for the current user."""
    environments = _load_environments(current_user.id)
    infos = [
        EnvironmentInfo(
            name=name,
            url=entry["url"],
            has_api_key=_entry_has_api_key(entry),
        )
        for name, entry in sorted(environments.items())
    ]
    return EnvironmentListResponse(environments=infos)


@router.post("/environments", response_model=EnvironmentListResponse, status_code=201)
async def add_environment(
    body: EnvironmentInput,
    current_user: CurrentActiveUser,
) -> EnvironmentListResponse:
    """Add a remote environment. The API key is encrypted at rest, never stored in plaintext."""
    name = body.name.strip()
    if not name:
        raise HTTPException(status_code=400, detail="Environment name is required.")
    environments = _load_environments(current_user.id)
    if name in environments:
        raise HTTPException(status_code=409, detail=f"Environment '{name}' already exists.")
    environments[name] = {
        "url": body.url.strip(),
        "api_key_encrypted": encrypt_api_key(body.api_key.strip()),
    }
    _write_environments(current_user.id, environments)
    return await list_environments(current_user)


@router.delete("/environments/{name}", response_model=EnvironmentListResponse)
async def remove_environment(
    name: str,
    current_user: CurrentActiveUser,
) -> EnvironmentListResponse:
    """Remove a remote environment."""
    environments = _load_environments(current_user.id)
    if name not in environments:
        raise HTTPException(status_code=404, detail=f"Environment '{name}' not found.")
    del environments[name]
    _write_environments(current_user.id, environments)
    return await list_environments(current_user)


@router.post("/login", response_model=LoginResponse)
async def login_environment(body: LoginRequest, current_user: CurrentActiveUser) -> LoginResponse:
    """Validate credentials against a remote environment (lfx login)."""
    entry = _resolve_env_or_404(current_user.id, body.env)
    api_key = _resolve_api_key(entry)
    project_dir = _project_dir(current_user.id)
    code, stdout, stderr = await _run_lfx(
        ["login", "--target", entry["url"], "--api-key", api_key],
        cwd=project_dir,
    )
    ok = code == 0
    message = (stdout.strip() or stderr.strip() or ("Authenticated." if ok else "Authentication failed.")).strip()
    if not ok:
        logger.warning(f"lfx login failed for env '{body.env}': {stderr.strip()}")
    return LoginResponse(ok=ok, message=message)


@router.get("/status", response_model=StatusResponse)
async def flow_status(
    current_user: CurrentActiveUser,
    session: DbSessionReadOnly,
    flow_id: Annotated[UUID, Query()],
    env: Annotated[str, Query()],
) -> StatusResponse:
    """Compare the local flow against a remote environment (lfx status)."""
    entry = _resolve_env_or_404(current_user.id, env)
    api_key = _resolve_api_key(entry)
    flow = await _fetch_user_flow(session, current_user.id, flow_id)
    project_dir = _project_dir(current_user.id)

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", dir=str(project_dir / "flows"), delete=False, encoding="utf-8"
    ) as tmp:
        json.dump(_flow_export_dict(flow), tmp)
        tmp_path = Path(tmp.name)
    try:
        _code, stdout, stderr = await _run_lfx(
            ["status", str(tmp_path), "--target", entry["url"], "--api-key", api_key],
            cwd=project_dir,
        )
    finally:
        tmp_path.unlink(missing_ok=True)

    # `lfx status` exits non-zero when out of sync; that is expected, not an error.
    status, detail = _parse_status(stdout)
    if status == "unknown" and stderr.strip():
        detail = stderr.strip()
    return StatusResponse(env=env, flow_id=flow_id, status=status, detail=detail)


@router.post("/apply", response_model=PromoteResponse)
async def promote_flow(
    body: PromoteRequest,
    current_user: CurrentActiveUser,
    session: DbSessionReadOnly,
) -> PromoteResponse:
    """Promote the local flow to a remote environment (lfx push, upsert by id)."""
    entry = _resolve_env_or_404(current_user.id, body.env)
    api_key = _resolve_api_key(entry)
    flow = await _fetch_user_flow(session, current_user.id, body.flow_id)
    project_dir = _project_dir(current_user.id)

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", dir=str(project_dir / "flows"), delete=False, encoding="utf-8"
    ) as tmp:
        json.dump(_flow_export_dict(flow), tmp)
        tmp_path = Path(tmp.name)

    args = ["push", str(tmp_path), "--target", entry["url"], "--api-key", api_key]
    if body.project:
        args += ["--project", body.project]
    try:
        code, stdout, stderr = await _run_lfx(args, cwd=project_dir)
    finally:
        tmp_path.unlink(missing_ok=True)

    ok = code == 0
    output = (stdout + ("\n" + stderr if stderr else "")).strip()
    if ok:
        message = f"Promoted '{flow.name}' to '{body.env}'."
    else:
        message = f"Promotion to '{body.env}' failed."
        logger.warning(f"lfx push failed for flow {body.flow_id} -> '{body.env}': {stderr.strip()}")
    return PromoteResponse(ok=ok, message=message, output=output)
